image: docker:19.03.1

services:
    - docker:19.03.1-dind

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    APP: centrox-ai-frontend-landing
    IMAGE_TAG: $CI_COMMIT_SHA
    RELEASE_IMAGE_TAG: release.$CI_COMMIT_SHA
    IMAGE_TAG_LATEST: latest
    IMAGE_PULL_SECRET: gitlab-registry-secret
    APP_NAME: "Centrox-AI-Frontend-Landing"
    STAGING_LINK: "https://staging.centrox.ai"
    PRODUCTION_LINK: "https://centrox.ai"
    NAMESPASE_PRODUCTION: "app-production-centrox-ai-frontend-landing"
    NAMESPASE_STAGING: "app-staging-centrox-ai-frontend-landing"
    SLACK_TEMPALTE_PATH: "ci/slack-templates/apk-update.json"


stages:
    - test
    - prerelease
    - build
    - deploy
    - build-release
    - deploy-release
    - release

test:
    stage: test
    image: node:16
    before_script:
        - npm install -g @commitlint/cli@18.4.3 @commitlint/config-conventional@18.4.3
    script:
        - echo "${CI_COMMIT_MESSAGE}" | commitlint -x $(npm root -g)/@commitlint/config-conventional
        - echo "sample tests running good!!!"
        - echo "CI_COMMIT_BRANCH:${CI_COMMIT_BRANCH}"

    tags:
        - any


prerelease:
    image: node:21-slim
    stage: prerelease
    before_script:
        - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
        - npm install -g semantic-release @semantic-release/gitlab
    script:
        - semantic_release_debug=$(semantic-release -d)
        - BUILD_VERSION=$(echo "$semantic_release_debug" | grep -oP 'Published release \K.*? ')
        - CHANGE_LOG=$(echo "$semantic_release_debug" | sed -n '/^##/,$p')
        - CHANGE_LOG_B64=$(echo "$CHANGE_LOG" | base64)
        - echo "CHANGE_LOG=> $CHANGE_LOG"
        - echo "CHANGE_LOG_B64=> $CHANGE_LOG_B64"
        - echo "BUILD VERSION=> '${BUILD_VERSION}'"
        - echo "BUILD_VERSION=$BUILD_VERSION" >> build.env
    artifacts:
      reports:
        dotenv: build.env
    only:
      - main
      - staging
    
    tags:
        - any


build-release:
    stage: build-release
    image:
        name: docker:24.0.5-dind
        entrypoint: [""]
    before_script:
        - docker info
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

    script:
        - echo "Recevied build version => '${BUILD_VERSION}'"
        - ENV_PATH="${CI_PROJECT_DIR}/.env"
        - printf "%s" "${PRODUCTION_ENV}" > "$ENV_PATH"
        - cat "$ENV_PATH"

        - tag="$CI_REGISTRY_IMAGE:${BUILD_VERSION}"
        - echo $tag

        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - docker image ls
        - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $tag --tag $CI_REGISTRY_IMAGE:latest .
        - docker push $tag
        - docker push $CI_REGISTRY_IMAGE:latest

        - echo "Docker Image pushed"
    only:
        - main
    tags:
        - any

deploy-release:
    stage: deploy-release
    image: dtzar/helm-kubectl:3.7.1
    environment:
        name: production
        url: http://centrox.ai/
    before_script:
        - echo "Recevied build version => '${BUILD_VERSION}'"
        - kubectl config get-contexts
        - kubectl config use-context  centrox-data-products/ai/centrox-ai-cluster-agent:centrox-ai-cluster-agent
        - kubectl get pods -A
        - KUBE_NAMESPACE="$NAMESPASE_PRODUCTION"
        - kubectl create namespace "$KUBE_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
        - "kubectl create secret -n $KUBE_NAMESPACE docker-registry ${IMAGE_PULL_SECRET} --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD --docker-email=$GITLAB_USER_EMAIL -o yaml --dry-run=client | kubectl replace --force -n $KUBE_NAMESPACE -f -"
    script:
        - cd deploy/
        - helm -n "$KUBE_NAMESPACE" upgrade --install -f values.production.yaml  ${APP} ./ --set image.name="$CI_REGISTRY_IMAGE" --set image.tag="${BUILD_VERSION}"
            --set image.pullsecret=${IMAGE_PULL_SECRET}
    only:
        - main

    tags:
        - any

build:
    stage: build
    image:
        name: docker:24.0.5-dind
        entrypoint: [""]
    before_script:
        - docker info
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:
        - echo "Recevied build version => '${BUILD_VERSION}'"
        - ENV_PATH="${CI_PROJECT_DIR}/.env"
        - printf "%s" "${STAGING_ENV}" > "$ENV_PATH"
        - cat "$ENV_PATH"

        - tag="$CI_REGISTRY_IMAGE:${BUILD_VERSION}"
        - echo $tag

        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - docker image ls
        - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $tag --tag $CI_REGISTRY_IMAGE:latest .
        - docker push $tag
        - docker push $CI_REGISTRY_IMAGE:latest
        
        - echo "Docker Image pushed"
    only:
        - staging
    tags:
        - any

deploy:
    stage: deploy
    image: dtzar/helm-kubectl:3.7.1
    environment:
        name: staging
        url: http://centrox.ai/
    before_script:
        - echo "Recevied build version => '${BUILD_VERSION}'"
        - kubectl config get-contexts
        - kubectl config use-context  centrox-data-products/ai/centrox-ai-cluster-agent:centrox-ai-cluster-agent
        - kubectl get pods -A
        - KUBE_NAMESPACE="$NAMESPASE_STAGING"
        - kubectl create namespace "$KUBE_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
        - "kubectl create secret -n $KUBE_NAMESPACE docker-registry ${IMAGE_PULL_SECRET} --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD --docker-email=$GITLAB_USER_EMAIL -o yaml --dry-run=client | kubectl replace --force -n $KUBE_NAMESPACE -f -"
    script:
        - cd deploy/
        - cat "./values.staging.yaml"
        - helm -n "$KUBE_NAMESPACE"  upgrade --install -f values.staging.yaml  ${APP} ./ --set image.name="$CI_REGISTRY_IMAGE" --set image.tag="${BUILD_VERSION}"
            --set image.pullsecret=${IMAGE_PULL_SECRET}
    only:
        - staging
    tags:
        - any

release:
    image: node:21-slim
    stage: release
    before_script:
        - echo "Recevied build version => '${BUILD_VERSION}'"
        - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates gettext-base curl
        - npm install -g semantic-release @semantic-release/gitlab
    script:
        - semantic_release_debug=$(semantic-release -d)
        - CHANGE_LOG=$(echo "$semantic_release_debug" | sed -n '/^##/,$p')
        - echo "CHANGE_LOG=> $CHANGE_LOG"

        - semantic-release

        - export BUILD_VERSION=${BUILD_VERSION}

        - echo "Recevied changelog => '${CHANGE_LOG}'"
        - FORMATED_CHANGE_LOG=$(echo "$CHANGE_LOG" | sed -e 's/\s*\*/- /g')
        - FORMATED_CHANGE_LOG=$(echo "$FORMATED_CHANGE_LOG" | sed -e 's/^###\s*Bug\s*Fixes/\*Bug Fixes\*/g')
        - FORMATED_CHANGE_LOG=$(echo "$FORMATED_CHANGE_LOG" | sed -e 's/^###\s*Features/\*Features\*/g')
        - FORMATED_CHANGE_LOG=$(echo "$FORMATED_CHANGE_LOG" | sed -e 's/\s*(\(.*\) (\(.*\)))/ <\2 | \1> /g')
        - echo "formated change log => '${FORMATED_CHANGE_LOG}'"
        - export FORMATED_CHANGE_LOG="$FORMATED_CHANGE_LOG"

        - export RELEASE="Staging"
        - '[ "$CI_COMMIT_BRANCH" = "main" ] && RELEASE="Production"'

        - export LINK="$STAGING_LINK"
        - '[ "$CI_COMMIT_BRANCH" = "main" ] && LINK="$PRODUCTION_LINK"'        

        - export DATETIME=$(date "+%Y-%m-%d_%H:%M:%SZ")
        - export BRANCH_NAME=${CI_MERGE_REQUEST_TITLE-${CI_COMMIT_BRANCH-'Branch Placeholder'}}
        
        - data=$(cat "$SLACK_TEMPALTE_PATH" | envsubst '$CI_PROJECT_TITLE $LINK $BRANCH_NAME $CI_COMMIT_SHORT_SHA $DATETIME $RELEASE $BUILD_VERSION $APP_NAME $FORMATED_CHANGE_LOG')
        
        - 'curl -X POST -H "Content-type: application/json" --data "$data" $SLACK_WEBHOOK'
    only:
      - main
      - staging

    tags:
        - any