replicas: 1

ingress:
  enabled: true
  tls:
    enabled: true
    secret_name: centrox-ai-frontend-landing-tls
  globalAnnotations: {}

  domains: []
    
service:
    name: centrox-ai-frontend-landing-service
    ports:
        target: 3000
        port: 80
        name: "80"

image:
    tag: latest
    name: ""
    pullsecret: gitlab-registry-secret

server:
    port: 3000
    session_secret: ""
    environment: production