replicas: 1

ingress:
    enabled: true
    domains: []
    secret_name: centrox-ai-staging-frontend-landing-tls
    issuer: letsencrypt-prod
    class: "nginx"
    tls: true
    annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        cert-manager.io/issue-temporary-certificate: "true"
        cert-manager.io/renew-before: 1440h
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/add-base-url: "true"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    

service:
    name: centrox-ai-frontend-landing-service
    ports:
        target: 3000
        port: 80
        name: "80"

image:
    tag: latest
    name: ""
    pullsecret: gitlab-registry-secret

server:
    port: 3000
    session_secret: ""
    environment: production