replicas: 1

ingress:
    enabled: true
    tls: true
    secret_name: centrox-ai-frontend-landing-tls
    domains:
        - "www.centrox.ai"
        - "centrox.ai"
    annotations:
        nginx.ingress.kubernetes.io/permanent-redirect: "https://www.centrox.ai"
        nginx.ingress.kubernetes.io/permanent-redirect-code: "301"

service:
    ports:
        target: 3000
        port: 80
        name: "80"

server:
    port: 3000
    session_secret: "ashdfjhasdlkjfhalksdjhflal"
    environment: production
